GET http://localhost:3000/games
###
GET http://localhost:3000/games?page=2&page_size=20
###
GET http://localhost:3000/games?filters[title]=Zelda
###
GET http://localhost:3000/games?filters[title]=Super Mario Odyssey
###
GET http://localhost:3000/games/70010000003781
###
GET http://localhost:3000/games/70010000003781/prices
###
GET http://localhost:3000/games/70010000003781/prices/PL
###
GET http://localhost:3000/games/70010000003781/prices/DE
###
GET http://localhost:3000/prices
